name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # هذه هي الكلمة السحرية التي ستسمح لك بتشغيله بضغطة زر

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # تنظيف بيئة جيت هوب من أي إعدادات تسبب خطأ 403
      - name: Remove local .npmrc (If exists)
        run: Remove-Item -Path .npmrc -ErrorAction SilentlyContinue

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund
        env:
          NODE_AUTH_TOKEN: ""

      - name: Build React App
        run: npm run build
        env:
          CI: false

      - name: Build Electron App (EXE)
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FastGrader-EXE
          path: release/*.exe
